Updating translation. Implementing proper configuration of dbconfig-common.

diff --git a/debian/config b/debian/config
--- a/debian/config
+++ b/debian/config
@@ -1,84 +1,93 @@
 #!/bin/bash -e
+#
+# ====================================================================
+# PACKAGE: aguilas
+# FILE: debian/config
+# DESCRIPTION:  Takes care of debconf and dbconfig-common questions to
+#		autoconfigure aguilas
+# USAGE: Executes automatically after package installation
+# COPYRIGHT:
+# (C) 2012 Luis Alejandro Martínez Faneyth <luis@huntingbears.com.ve>
+# LICENCE: GPL3
+# ====================================================================
+#
+# This program is free software: you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation, either version 3 of the License, or
+# (at your option) any later version.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
+# COPYING file for more details.
+#
+# You should have received a copy of the GNU General Public License
+# along with this program. If not, see <http://www.gnu.org/licenses/>.
+#
+# CODE IS POETRY
 
-CONFFILE="/etc/aguilas/config.php"
+if [ "${AGUILASDEBUG}" == "true" ]; then
+	set -x
+fi
 
 . /usr/share/debconf/confmodule
 db_version 2.0 || [ $? -lt 30 ]
 
-if [ ! -f ${CONFFILE} ]; then
+if [ -f /etc/dbconfig-common/aguilas.conf ] ; then
+	. /etc/dbconfig-common/aguilas.conf
+fi
 
-	db_input medium aguilas/app-mail || true
-	db_go || true
-	db_get aguilas/app-mail || true
-	APPMAIL="${RET}"
-	db_set aguilas/app-mail ${APPMAIL} || true
+if [ -f /usr/share/dbconfig-common/dpkg/config.mysql ]; then
+       	. /usr/share/dbconfig-common/dpkg/config.mysql
 
-	db_input medium aguilas/app-url || true
-	db_go || true
-	db_get aguilas/app-url || true
-	APPURL="${RET}"
-	db_set aguilas/app-url ${APPURL} || true
+	if [ "${AGUILASDEBUG}" == "true" ]; then
+		dbc_debug=1
+	fi
 
+	dbc_first_version="1.0.1-1"
+	dbc_load_include="php:/etc/aguilas/dbconfig-common.php"
+	dbc_load_include_args="-dmysql_dbname -smysql_host -pmysql_pass -umysql_user"
+	dbc_dbtypes="mysql"
+	dbc_dbname="aguilas"
+	dbc_dbuser="aguilas"
+
+        if ! dbc_go aguilas $@ ; then
+       	    echo 'Automatic configuration using dbconfig-common failed!'
+	fi
+fi
+
+if [ -z ${dbc_dbserver} ]; then
 	db_input medium aguilas/mysql-server || true
-	db_input medium aguilas/mysql-user || true
+	db_go || true
+fi
+
+if [ -z ${dbc_dbpass} ]; then
 	db_input medium aguilas/mysql-pass || true
 	db_go || true
-	db_get aguilas/mysql-server || true
-	MYSQLSERVER="${RET}"
-	db_get aguilas/mysql-user || true
-	MYSQLUSER="${RET}"
-	db_get aguilas/mysql-pass || true
-	MYSQLPASS="${RET}"
-	db_set aguilas/mysql-server ${MYSQLSERVER} || true
-	db_set aguilas/mysql-server ${MYSQLUSER} || true
-	db_set aguilas/mysql-server ${MYSQLPASS} || true
-
-	db_input medium aguilas/ldap-server || true
-	db_go || true
-	db_get aguilas/ldap-server || true
-	LDAPSERVER="${RET}"
-	db_set aguilas/ldap-server ${LDAPSERVER} || true
-
-	db_input medium aguilas/ldap-base || true
-	db_go || true
-	db_get aguilas/ldap-base || true
-	LDAPBASE="${RET}"
-	db_set aguilas/ldap-base ${LDAPBASE} || true
-	
-	db_set aguilas/ldap-bind "cn=admin,${LDAPBASE}"
-	db_input medium aguilas/ldap-bind || true
-	db_go || true
-	db_get aguilas/ldap-bind || true
-	LDAPBIND="${RET}"
-	db_set aguilas/ldap-bind ${LDAPBIND} || true
-
-	db_input medium aguilas/ldap-pass || true
-	db_go || true
-	db_get aguilas/ldap-pass || true
-	LDAPPASS="${RET}"
-	db_set aguilas/ldap-pass ${LDAPPASS} || true
-
-	db_input medium aguilas/reconfigure-webserver || true
-	db_go || true
-	db_get aguilas/reconfigure-webserver || true
-	WEBSERVERS="${RET}"
-	db_set aguilas/reconfigure-webserver ${WEBSERVERS} || true
-
-	db_input medium aguilas/restart-webserver || true
-	db_go || true
-	db_get aguilas/restart-webserver || true
-	RESTART="${RET}"
-	db_set aguilas/restart-webserver ${RESTART} || true
-
-	if [ -f /usr/share/dbconfig-common/dpkg/config.mysql ]; then
-        	. /usr/share/dbconfig-common/dpkg/config.mysql
-		dbc_load_include="php:/etc/aguilas/dbc.php"
-	        if ! dbc_go aguilas $@ ; then
-	       	    echo 'Automatic configuration using dbconfig-common failed!'
-		fi
-        fi
-
 fi
+
+db_input medium aguilas/ldap-server || true
+db_go || true
+
+db_input medium aguilas/ldap-base || true
+db_go || true
+db_get aguilas/ldap-base || true
+LDAPBASE="${RET}"
+
+db_set aguilas/ldap-bind "cn=admin,${LDAPBASE}"
+db_input medium aguilas/ldap-bind || true
+db_go || true
+
+db_input medium aguilas/ldap-pass || true
+db_go || true
+
+db_input medium aguilas/reconfigure-webserver || true
+db_go || true
+
+db_input medium aguilas/restart-webserver || true
+db_go || true
+
+db_stop || true
 
 #DEBHELPER#
 
diff --git a/debian/postrm b/debian/postrm
--- a/debian/postrm
+++ b/debian/postrm
@@ -1,23 +1,62 @@
 #! /bin/bash -e
+#
+# ====================================================================
+# PACKAGE: aguilas
+# FILE: debian/postrm
+# DESCRIPTION: Removes/purges conffiles after package uninstallation
+# USAGE: Executes automatically after package uninstallation
+# COPYRIGHT:
+# (C) 2012 Luis Alejandro Martínez Faneyth <luis@huntingbears.com.ve>
+# LICENCE: GPL3
+# ====================================================================
+#
+# This program is free software: you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation, either version 3 of the License, or
+# (at your option) any later version.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
+# COPYING file for more details.
+#
+# You should have received a copy of the GNU General Public License
+# along with this program. If not, see <http://www.gnu.org/licenses/>.
+#
+# CODE IS POETRY
 
 ACTION="${1}"
 VERSION="${2}"
 
+if [ "${AGUILASDEBUG}" == "true" ]; then
+	set -x
+fi
+
+. /usr/share/debconf/confmodule
+db_version 2.0 || [ $? -lt 30 ]
+
+if [ -f /etc/dbconfig-common/aguilas.conf ] ; then
+	. /etc/dbconfig-common/aguilas.conf
+fi
+
 if [ "${ACTION}" == "remove" ] || [ "${ACTION}" == "purge" ]; then
 
-	. /usr/share/debconf/confmodule
-	db_version 2.0 || [ $? -lt 30 ]
+	if [ -f /usr/share/dbconfig-common/dpkg/postrm.mysql ]; then
+		. /usr/share/dbconfig-common/dpkg/postrm.mysql
 
-	. /usr/share/dbconfig-common/dpkg/postrm.mysql
+		if [ "${AGUILASDEBUG}" == "true" ]; then
+			dbc_debug=1
+		fi
 
-	if ! dbc_go aguilas $@ ; then
-		echo 'Automatic configuration using dbconfig-common failed!'
+		if ! dbc_go aguilas $@ ; then
+			echo 'Automatic configuration using dbconfig-common failed!'
+		fi
 	fi
 
 	db_get aguilas/reconfigure-webserver || true
 	WEBSERVER="${RET}"
 
-	db_get phpldapadmin/restart-webserver || true
+	db_get aguilas/restart-webserver || true
 	RESTART="${RET}"
 
 	db_stop || true
@@ -32,14 +71,14 @@ if [ "${ACTION}" == "remove" ] || [ "${ACTION}" == "purge" ]; then
 				if [ -f /etc/lighttpd/conf-available/50-aguilas.conf ]; then
 					if which lighty-disable-mod >/dev/null 2>&1; then
 						lighty-disable-mod aguilas
-						rm -f /etc/lighttpd/conf-available/50-aguilas.conf
+						rm -rf /etc/lighttpd/conf-available/50-aguilas.conf
 					else
 						echo "Lighttpd not installed, skipping"
 					fi
 				fi
 
 				if [ -h /etc/lighttpd/conf-enabled/50-aguilas.conf ] ; then
-					rm /etc/lighttpd/conf-enabled/50-aguilas.conf
+					rm -rf /etc/lighttpd/conf-enabled/50-aguilas.conf
 				fi
 			;;
 
@@ -62,23 +101,25 @@ fi
 
 if [ "${ACTION}" == "purge" ]; then
 
-	rm -f /usr/share/aguilas/setup/config.php
-
 	for ext in '~' '%' .bak .ucf-new .ucf-old .ucf-dist;  do
-		rm -f /etc/aguilas/config.php$ext
+		rm -rf /etc/aguilas/config.php$ext
 	done
-
-	rm -f /etc/aguilas/config.php
-
-	if which ucf >/dev/null; then
-		ucf --debconf-ok --purge /etc/aguilas/config.php
-	fi
-	if which ucfr >/dev/null; then
-		ucfr --purge aguilas /etc/aguilas/config.php
-	fi
 
 	rm -rf /etc/aguilas
 	rm -rf /var/log/aguilas
+	rm -rf /usr/share/aguilas/setup/config.php
+
+	if which ucf >/dev/null; then
+		ucf --debconf-ok --purge /etc/aguilas/config.php
+		ucf --debconf-ok --purge /etc/aguilas/dbconfig-common.php
+	fi
+
+	if which ucfr >/dev/null; then
+		ucfr --purge aguilas /etc/aguilas/config.php
+		ucfr --purge aguilas /etc/aguilas/dbconfig-common.php
+	fi
+
+	db_purge
 fi
 
 #DEBHELPER#
